### ISSUE TITLE
Executor self-tests fail: Protection fault on: 334 (sys_rseq)

### ISSUE THREAD

**Issue by PhilipLu97** [DMOJ/judge-server#1032]
When I try running `dmoj -c judge.yml localhost` from the directory where judge.yml is stored, I get the following output: 

Self-testing executors
Self-testing AWK:    Failed  [0.002s, 992 KB]    awk 5.1.1
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554fd4460
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing BF:     Failed  [0.002s, 424 KB]    bf 1.33.7
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555552dd0e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing C:      Failed  [0.002s, 496 KB]    gcc 11.2.0
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555551f50e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing CLANG:  Failed  [0.002s, 496 KB]    clang 13.0.1
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555551f50e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing CLANGX: Failed  [0.002s, 704 KB]    clang++ 13.0.1
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554fb20e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing CPP03:  Failed  [0.003s, 672 KB]    g++ 11.2.0
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554fb20e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing CPP11:  Failed  [0.003s, 672 KB]    g++11 11.2.0
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554fb20e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing LUA:    Failed  [0.002s, 788 KB]    lua 5.4.4
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555551240e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing PERL:   Failed  [0.003s, 820 KB]    perl 5.34.1
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554e32ca0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000090
Self-testing PHP:    Failed  [0.003s, 2024 KB]   php 8.1.4
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155552a440e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing PY3:    Failed  [0.002s, 772 KB]    python3 3.10.4
Protection fault on: 334 (sys_rseq)
Arg0: 0x0000155554e3b520
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000090
Self-testing SED:    Failed  [0.002s, 448 KB]    sed 4.8
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555552d30e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000
Self-testing TCL:    Failed  [0.003s, 592 KB]    tclsh 8.6
Protection fault on: 334 (sys_rseq)
Arg0: 0x00001555550360e0
Arg1: 0x0000000000000020
Arg2: 0x0000000000000000
Arg3: 0x0000000053053053
Arg4: 0x0000000000000000
Arg5: 0x0000000000000000

Running live judge...
INFO 2022-04-25 20:15:13,953 32547 packet Preparing to connect to [localhost]:9999 as: test
INFO 2022-04-25 20:15:13,953 32547 packet TLS not enabled.
INFO 2022-04-25 20:15:13,953 32547 packet Opening connection to: [localhost]:9999
INFO 2022-04-25 20:15:13,955 32547 packet Starting handshake with: [localhost]:9999
INFO 2022-04-25 20:15:13,955 32547 packet Awaiting handshake response: [localhost]:9999
INFO 2022-04-25 20:15:13,958 32547 packet Judge "test" online: [localhost]:9999
INFO 2022-04-25 20:15:13,958 32547 monitor Scheduled for monitoring: [my directory] 

I generally understand protection faults to mean that multiple processes are trying to use the same address in RAM at the same time, causing a conflict. Using tools such as gdb, devmem, hexdump, etc. to investigate the "Args" printed in the output above, I have found some clues, but nothing conclusive:

1. Every Arg0 above leads to `devmem: mmap: Invalid argument` or `hexdump: /dev/mem: Bad address`, which seems to imply that they are all actual values, not addresses to places in user space memory. Converting these values to decimal just yields really large numbers, so I don't know what they mean.
2. Every Arg1 above translates to 32 in decimal (32 bit?). Reading that specific memory address just returns 0, so there is presumably nothing there of interest. 
3. Every Arg3 above (0x0000000053053053) is the same; this arg is likely the most important piece of the puzzle because I can't read what is at that address due to the kernel not allowing more than 1MB of data to be read from RAM at a time. I believe this means that a file is stored there or one of the other services/processes on my computer is taking up that address space. 

Every time I restart the judge with`dmoj -c judge.yml localhost` , the same output gets printed every time. 

Some other info that may be useful: 

- In my case, the pid for the judge is 32547 and is a subprocess of the user service for my user, which has pid 663 (systemd). I've started to look through the directory for pid 32547 (under /proc/663/root/proc/32547), but I'm not sure if I'll find anything. People say reading the mem file in that directory will help, but I haven't been able to do so. 

- My judge.yml file is set up like so, more or less similar to the sample config file provided by you guys (I have properly configured the problem storage root in local_settings.py, and nginx, supervisord, mariadb, and redis are all running successfully; I use uwsgi_pass in nginx.conf to pass traffic upstream to django): 

id: test
key: [generated from admin page]

runtime:
  as_x64: /usr/bin/as
  as_x86: /usr/bin/as
  ld_x64: /usr/bin/ld
  ld_x86: /usr/bin/ld
  nasm: /usr/bin/nasm
From sample judge_conf.yml
  ccl: /opt/ccl/lx86cl
  sed: /bin/sed
  awk: /usr/bin/awk
  gnatmake: /usr/bin/gnatmake
  chicken-csc: /usr/bin/csc
  dart: /opt/dart-sdk/bin/dart
  tclsh: /usr/bin/tclsh
  cobc: /usr/bin/cobc
  erl: /usr/bin/erl
  erlc: /usr/bin/erlc
  tprolog: /opt/turing/tprolog/tprolog
  tprologc: /opt/turing/tprolog/tprologc
  turing_dir: /opt/turing/tprolog
  node: /usr/bin/node
  lua: /usr/bin/lua
  ocaml: /usr/bin/ocamlopt
  pypy: /opt/pypy/bin/pypy
  pypydir: /opt/pypy/
  pypy3: /opt/pypy3/bin/pypy
  pypy3dir: /opt/pypy3/
  ghc: /usr/bin/ghc
  go: /usr/bin/go
  fsharpc: /usr/bin/fsharpc
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  mono: /usr/bin/mono
  dmd: /usr/bin/dmd
  fpc: /opt/fpc-2.6.4/bin/fpc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /opt/gcc-5.1.0/bin/g++
  gfortran: /usr/bin/gfortran
  nasm: /usr/bin/nasm
  ld: /usr/bin/ld
  python: /opt/python27/bin/python2.7
  python2dir: /opt/python27/
  python3: /usr/bin/python3
  python3dir: /opt/python34/
  java: /usr/lib/jre1.8.0_321/bin/java
  javac: /usr/bin/javac
  java8: /usr/lib/jre1.8.0_321/bin/java
  javac8: /usr/lib/jvm/jdk-8-oracle-i586/bin/javac
Custom V8 build to facilitate online judging: https://github.com/DMOJ/v8dmoj
  v8dmoj: /home/judge/judge/executors/v8dmoj
  php: /usr/bin/php
  phpconfdir: /etc/php5/
  perl: /usr/bin/perl
  ruby19: /usr/bin/ruby1.9.1
  ruby21: /usr/bin/ruby
  racket: /opt/racket/bin/racket
  raco: /opt/racket/bin/raco
  racket-lib: /opt/racket/lib
  gnustep-config: /usr/bin/gnustep-config
  gobjc: /usr/bin/gcc

problem_storage_root: 
  - [root]

- Tests of single executors fail too (i.e. only having the CLANG executor configured in judge.yml still leads to failure) with the same protection fault (334) occurring 

- Self-tests also fail when running the dmoj binary as the user dedicated to running the DMOJ website 

- Linux distro is Manjaro, but I still have all the necessary dependencies for the server installed from community repos

I've been trying to solve this issue for a while, but I haven't gotten anywhere. Could you guys help me? I would really appreciate it.

**Comment by Xyene** [comment]
This was fixed in https://github.com/DMOJ/judge-server/commit/b3b0c28b51035790c9523af4c5952d2f0b196088, you should just have to upgrade past that.
