### ISSUE TITLE
cannot understand handshake response

### ISSUE THREAD

**Issue by kumarshubham01** [DMOJ/judge-server#1035]
I have tried everything like changing the port to changing the BRIDGED_JUDGE_ADDRESS but still facing the same issue here is my error log.

`` INFO 2022-07-18 22:30:56,753 9964 packet Preparing to connect to [localhost]:9999 as: testJudge
INFO 2022-07-18 22:30:56,753 9964 packet TLS not enabled.
INFO 2022-07-18 22:30:56,753 9964 packet Opening connection to: [localhost]:9999
INFO 2022-07-18 22:30:56,756 9964 packet Starting handshake with: [localhost]:9999
INFO 2022-07-18 22:30:56,756 9964 packet Awaiting handshake response: [localhost]:9999
ERROR 2022-07-18 22:30:56,761 9964 packet Cannot understand handshake response: [localhost]:9999
Traceback (most recent call last):
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 288, in handshake
    size = PacketManager.SIZE_PACK.unpack(data)[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2022-07-18 22:30:56,761 9964 packet Authentication as "testJudge" failed on: [localhost]:9999
WARNING 2022-07-18 22:30:56,761 9964 packet Attempting reconnection in 4s: [localhost]:9999
INFO 2022-07-18 22:30:56,761 9964 packet Dropping old connection.
INFO 2022-07-18 22:31:00,763 9964 packet Opening connection to: [localhost]:9999
INFO 2022-07-18 22:31:00,763 9964 packet Starting handshake with: [localhost]:9999
INFO 2022-07-18 22:31:00,764 9964 packet Awaiting handshake response: [localhost]:9999
ERROR 2022-07-18 22:31:00,768 9964 packet Cannot understand handshake response: [localhost]:9999
Traceback (most recent call last):
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 288, in handshake
    size = PacketManager.SIZE_PACK.unpack(data)[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 129, in _do_reconnect
    self._connect()
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 114, in _connect
    self.handshake(problems, versions, self.name, self.key)
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 293, in handshake
    raise JudgeAuthenticationFailed()
dmoj.packet.JudgeAuthenticationFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erworks/dmojsite/lib/python3.8/site-packages/dmoj/packet.py", line 288, in handshake
    size = PacketManager.SIZE_PACK.unpack(data)[0]
struct.error: unpack requires a buffer of 4 bytes
ERROR 2022-07-18 22:31:00,769 9964 packet Authentication as "testJudge" failed on: [localhost]:9999
WARNING 2022-07-18 22:31:00,769 9964 packet Attempting reconnection in 6s: [localhost]:9999
INFO 2022-07-18 22:31:00,769 9964 packet Dropping old connection.
``

**Comment by kumarshubham01** [comment]
Problem is solved but I am not able to figure out any proper solution it’s took up a lot of try from modifying local_setting.py to restarting and stopping ports I have done what ever I can do resulting the problem is solved but unable to figure out proper solutions

**Comment by ad1tya2** [comment]
I have the same issue and restarting or changing anything does not seem to be working
