### ISSUE TITLE
Judge online, but not available for problems

### ISSUE THREAD

**Issue by adaptNYP** [DMOJ/judge-server#1099]
I managed to get a judge online with a number of languages configured, specifically Python 3 which I want to use.

However, using the example aplusb problem, even while selecting all languages allowed, I do not see the judge that is online being available to use. After clicking on the "Submit solution" button, the screen shows in red text "No judge is available for this problem".

Anyone can help?
![Capture](https://user-images.githubusercontent.com/58022041/212298807-f390d2a2-32cf-4525-bbb0-52419e13cda0.JPG)
![Capture2](https://user-images.githubusercontent.com/58022041/212298829-a53db2dd-32a0-4ad9-8b2f-9b94b4aa841d.JPG)
![Capture3](https://user-images.githubusercontent.com/58022041/212298854-69a892c7-325b-4a98-88ce-4db41353693a.JPG)

**Comment by adaptNYP** [comment]
Problem solved following advice given in #399

**Comment by Elfsong** [comment]
> Problem solved following advice given in #399

It's not the same question. I can't find any problem in my /mnt/problems

**Comment by kiritofeng** [comment]
You 

> > Problem solved following advice given in #399
> 
> It's not the same question. I can't find any problem in my /mnt/problems

It seems like you've either put your problem data into a different folder, or you haven't configured testdata.

In the former case, you should replace `/mnt/problems` with the correct path, and in the latter, you should add testdata. Sample testdata for `aplusb` can be found [here](https://github.com/DMOJ/judge-server/tree/master/testsuite/aplusb).
