### ISSUE TITLE
CPP03 does not use C++03 dialect

### ISSUE THREAD

**Issue by hieplpvip** [DMOJ/judge-server#1108]
`std` is not set to `c++03` in `CPP03.py`: https://github.com/DMOJ/judge-server/blob/96b2fffea81d84dd0f6c7f6a3f0d12a5900fb562/dmoj/executors/CPP03.py#L8

Hence CPP03 would actually use the default C++ dialect, which is C++17 for GCC 12. This is confirmed by compiling the test program for CPP17:
- C++03: https://dmoj.ca/submission/5267665 (compile ok)
- C++14: https://dmoj.ca/submission/5267672 (compile error)

**Comment by Xyene** [comment]
Thanks for the report!
