### ISSUE TITLE
I Can't install make judge-tier1

### ISSUE THREAD

**Issue by huunambg** [DMOJ/judge-server#1114]
![image](https://user-images.githubusercontent.com/98996472/221632021-e5de756f-08a1-488e-983f-7528a5e0e661.png)

**Comment by hieplpvip** [comment]
Ref: https://github.com/python/cpython/issues/102134

You can work around this by modifying Dockerfile to pass the flag `--break-system-packages` to `pip`: `pip3 install --break-system-packages -e .`

Normally this is not recommended but we're running inside the container so it should be ok. Not sure how to properly fix this though.

**Comment by Xyene** [comment]
I believe this should be fixed as of https://github.com/DMOJ/runtimes-docker/commit/8fe75f131ef4c72be91e32c0164dd9a2b560b1d0

**Comment by Xyene** [comment]
Ah, sorry, the same fix needs to be done in this repo.
