### ISSUE TITLE
How to install additional packages for judge env (e.g. scipy, numpy)

### ISSUE THREAD

**Issue by adaptNYP** [DMOJ/judge-server#1116]
Hi, 

I needed the `scipy` module for some of the judging, so I wanted to include it into the judge.

I was referring to #865 , but as I am not using the docker version of the judge (I installed the judge using the PyPI instructions), I do not know where to find the executor code to modify. 

Can someone walk me through how to include other modules for judging for judges not installed using docker?

Thanks a lot in advance.

**Comment by Xyene** [comment]
> I was referring to https://github.com/DMOJ/judge-server/issues/865 , but as I am not using the docker version of the judge (I installed the judge using the PyPI instructions), I do not know where to find the executor code to modify.

If you are going to do this, you should install from the git repository rather than PyPI. Don't try to use the PyPI version in this way, it will break terribly the next time we push an update and your packages update.

#865 shows how to do this with an install off this git repository.
