### ISSUE TITLE
Latest watchdog would trigger on_opened events

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/judge-server#1129]
Latest commit from watchdog: https://github.com/gorakhargosh/watchdog/commit/f3dfc4be0c6ec36c2db6b4afa075004e71adf87e

It means `SendProblemsHandler.on_any_event` in `monitor.py` would also trigger `on_opened`. Judges need to trigger this to read test data and init file. This leads to `supported-problems` being sent multiple times on every submission. Suppose there are n judges, bridged will receive at least 2 * n  `supported-problems` packets on each submission, which leads to 2n SQL update queries.

One simple fix is to add this line in `SendProblemsHandler.on_any_event`.
```python
def on_any_event(self, event):
        if event.event_type == "opened":
            return
        if self.callback is not None:
            self.callback()
        if self.refresher is not None:
            self.refresher.refresh()
```

**Comment by Xyene** [comment]
That sounds reasonable, but I think rather than comparing against `opened` and bailing, we should compare against the set of events we do care about (in case `watchdog` adds more events in the future)

Would you be willing to submit a patch?

**Comment by Xyene** [comment]
Fixed in https://github.com/DMOJ/judge-server/commit/17b0bcf3a0a79045e8dedfcbf2b47f4e2e724f93.
