### ISSUE TITLE
all

### ISSUE THREAD

**Issue by phanvanchung** [DMOJ/judge-server#1135]
FROM dmoj/runtimes-tier1

ARG TAG=master
RUN mkdir /judge && cd /judge && \
	curl -L https://github.com/DMOJ/judge/archive/"${TAG}".tar.gz | tar -xz --strip-components=1 && \
	pip3 install -e . && \
	runuser -u judge -w PATH -- dmoj-autoconf -V > /judge-runtime-paths.yml && \
	echo '  crt_x86_in_lib32: true' >> /judge-runtime-paths.yml

ENTRYPOINT ["/judge/.docker/entry"]

**Comment by kiritofeng** [comment]
It is not clear what the issue here is. If necessary, please re-open and clearly state your issue.
