### ISSUE TITLE
Add support for Node.js

### ISSUE THREAD

**Issue by chinesedfan** [DMOJ/judge-server#1136]
It will be better than V8 JavaScript. Or can you give some tips for other contributors to implement this feature?

**Comment by Xyene** [comment]
If you take a look at https://github.com/DMOJ/judge-server/tree/master/dmoj/executors, there are a lot of examples for different runtimes. You'd need to create a `NODEJS.py` file, probably deriving from `ScriptExecutor`, and fill in everything necessary.

**Comment by Xyene** [comment]
Implemented in #1143.
