### ISSUE TITLE
Is this judge server can be deployed in a independent server to provide  API service for other judge platform?

### ISSUE THREAD

**Issue by alexwenbj** [DMOJ/judge-server#1142]
Hi, I have a question,is this judge server can be deployed in a independent server as the back-end judge service,just like judge0 judge server?Thank you.

**Comment by alexwenbj** [comment]
> If you can adapt the API, then yes.

Thank you for your rapid answer.Where can I find the docs to deploy?

**Comment by kiritofeng** [comment]
https://docs.dmoj.ca/#/judge/setting_up_a_judge
