### ISSUE TITLE
Dockerized version of the judge

### ISSUE THREAD

**Issue by Maitre-Hiboux** [DMOJ/judge-server#392]
Hello,

I created for a recreational use inside my company a dockerized version of the judge (and of the site, see issue in DMOJ/site ) that is intended to work offline behind proxies and in containers. It is not perfect at all but at least it is working and I am still working on improving it. I thought you may be interested so I came here to bring it to you.

https://github.com/Maitre-Hiboux/dmoj-judge-docker

**Comment by kiritofeng** [comment]
Closing as we have Docker support.
