### ISSUE TITLE
Ability to remove access to certain libraries and modules for some problems

### ISSUE THREAD

**Issue by UserBlackBox** [DMOJ/judge-server#581]
Having the ability to remove certain libraries from a problem would be useful for making solvers create algorithms from scratch rather than using built-ins

**Comment by ehhthing** [comment]
To effectively do this, you would have to implement a security system for every single programming language that DMOJ supports. Most of these languages have to in built way to blacklist modules. Further, many (like CoffeeScript/NodeJS) automatically load all modules into memory at launch meaning that there is no way to effectively block them.

Given this, feel free to PR a solution if you have it.

**Comment by kiritofeng** [comment]
I am closing this ticket as the amount of effort required to support this feature in the general case is very disproportionate when compared to the benefits.
