### ISSUE TITLE
submission `pid` can be zero causing the judge to kill itself on a requested abort

### ISSUE THREAD

**Issue by Ninjaclasher** [DMOJ/judge-server#588]
If a user aborts a submission before the pid is set [here](https://github.com/DMOJ/judge-server/blob/67e856d0dd7f284d9f825ea67df7030380976b1a/dmoj/cptbox/ptproc.cpp#L84), then `os.killpg(0, signal.SIGKILL)` kills the judge itself.

According to @Xyene, the solution would be to remove `with nogil:` [here](https://github.com/DMOJ/judge-server/blob/c4b5e52665dfb6100dfa2de7429a05fd1a72ae7f/dmoj/cptbox/_cptbox.pyx#L433-L434), though this change needs to be tested before it is removed.

**Comment by Xyene** [comment]
Easy way to reproduce: take a problem with a lot of testcases, and write a program that IRs quickly on everything. Spam `$('input[class=button]').click();` in console. Took only 10 tries to reproduce on https://dmoj.ca/submission/1703630.
