### ISSUE TITLE
Non-binary scoring for `bridged` checker

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/judge-server#598]
Currently, the `bridged` checker does not allow for anything other than binary scoring: return code `0` is full points, and `1` or `2` is WA/PE. How should this be modified to allow for non-binary scoring?

**Comment by kiritofeng** [comment]
This can be added as a member of `contrib`.

**Comment by Xyene** [comment]
Was this resolved by https://github.com/DMOJ/judge-server/commit/ccbeecb2feac4f3a8a57af8627e49dfc28dbedc7?

**Comment by kiritofeng** [comment]
Yes, closing.
