### ISSUE TITLE
Limit memory usage of compilers

### ISSUE THREAD

**Issue by ehhthing** [DMOJ/judge-server#599]
Compilers can OOM, which can cause judges to crash.

**Comment by Xyene** [comment]
The correct place for this to go is here:

https://github.com/DMOJ/judge-server/blob/f0b6668d1c85e5c64ad4604dce7fac11e1c3395c/dmoj/executors/compiled_executor.py#L138

We might also want to tweak the OOM score (`/proc/self/oom_score_adj`), writing in `OOM_SCORE_ADJ_MAX` (1000).
