### ISSUE TITLE
Question is it possible to the judge to use database instead of filesystem /mnt/problems

### ISSUE THREAD

**Issue by animesh-sharama** [DMOJ/judge-server#701]
Is is possible to read problems from a database rather than a file system.
I got the site and the judge running on a different machine.
```
docker run \
    -v /mnt/problems:/problems \
    --cap-add=SYS_PTRACE \
    -c /problems/judge.yml \
    dmoj/judge-tier1:latest \
    cli
```
I wanted to know if the judge can use a database instead of filesystem for problems?
I am new to python any pointer within the judge-server code where the changes can be potentially made to use database for problem instead of file system would be really helpful?

**Comment by ehhthing** [comment]
In theory you can do this with [MySQLfs](https://github.com/bianster/mysqlfs), but I wouldn't recommend it.

**Comment by animesh-sharama** [comment]
@ehhthing I was thinking if I can replicate the file system functionality used by the judge over an actual database which can be remote as well.

**Comment by Xyene** [comment]
There is no built-in support for something like this. Fundamentally, most databases are not designed for storage and retrieval of large binary blobs, which is what storing testdata in one would amount to; most indeed recommend splitting out such large blobs to the filesystem instead.

If you are set on doing this for a particular reason, you would need to modify the [`Problem`](https://github.com/DMOJ/judge-server/blob/master/dmoj/problem.py#L24) class to retrieve problem data by ID, and the [problem scanner](https://github.com/DMOJ/judge-server/blob/master/dmoj/judgeenv.py#L285) to report to the site what problems are available.

Having said that, the recommended deployment scheme for multi-judge setups is via NFS (or a similar networked filesystem; NFS has an advantage of being in-kernel and more performant than FUSE-based filesystems, and is what we run on [dmoj.ca](https://dmoj.ca)), using the judge API endpoint to signal problem updates from the NFS server (as inotify is nonfunctional for network mounts).
