### ISSUE TITLE
Return errno directly with seccomp filters

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge-server#793]
`libseccomp`'s `seccomp_rule_add` supports an action called `SCMP_ACT_ERRNO(errno)`, so all our handlers that generates `errno`s could theoretically be handled in seccomp.

**Comment by Xyene** [comment]
I considered this before, but I don't think we have a good enough ptbox testing story currently. I'd be worried about the ptrace-only errno implementations bitrotting unnoticed.

**Comment by Xyene** [comment]
Given https://github.com/DMOJ/judge-server/issues/871 is in the pipeline, we can commit to dropping the ptrace-only backend and go ahead with this.
