### ISSUE TITLE
running local judge success in docker but online status inactive

### ISSUE THREAD

**Issue by armornet** [DMOJ/judge-server#823]
Hello,
i have placed judge.yml with judge name and key generated from site in the below path

/mnt/problems/problems/judge.yml

i installed judge-tier1 using the below command as given in the documentation

`
git clone --recursive https://github.com/DMOJ/judge.git
$ cd judge/.docker
$ make judge-tier1
$ docker run \
    -v /mnt/problems:/problems \
    --cap-add=SYS_PTRACE \
    dmoj/judge-tier1:latest \
    cli -c /problems/judge.yml
`
and here is the output

`
root@video:~/judge/.docker# docker run     -v /mnt/problems:/problems     --cap-add=SYS_PTRACE     dmoj/judge-tier1:latest     cli -c /problems/judge.yml
Self-testing executors
Self-testing AWK:    Success [0.008s, 936 KB]    awk 1.3.4
Self-testing BF:     Success [0.006s, 588 KB]    bf 1.33.7
Self-testing C:      Success [0.005s, 532 KB]    gcc 10
Self-testing C11:    Success [0.006s, 532 KB]    gcc11 10
Self-testing CPP03:  Success [0.008s, 1532 KB]   g++ 10
Self-testing CPP11:  Success [0.008s, 1608 KB]   g++11 10
Self-testing CPP14:  Success [0.007s, 1536 KB]   g++14 10
Self-testing CPP17:  Success [0.007s, 1540 KB]   g++17 10
Self-testing GAS64:  Success [0.007s, 4 KB]      as_x64 2.35.1, ld_x64 2.35.1
Self-testing JAVA8:  Success [0.335s, 33788 KB]  javac 1.8.0
Self-testing PAS:    Success [0.006s, 4 KB]      fpc 3.2.0
Self-testing PERL:   Success [0.025s, 5960 KB]   perl 5.32.0
Self-testing PY2:    Success [0.047s, 6332 KB]   python 2.7.18
Self-testing PY3:    Success [0.086s, 9520 KB]   python3 3.9.1
Self-testing SED:    Success [0.009s, 728 KB]    sed 4.7
Self-testing TEXT:   Success [0.010s, 1888 KB]   cat 8.32

Running local judge...
`

but judge unable to connect to the judge site

Any advise please

**Comment by kiritofeng** [comment]
RTFM

**Comment by armornet** [comment]
i have done everything according to the documentation only... your [RTFM] but still unable to connect..
