### ISSUE TITLE
live judge error

### ISSUE THREAD

**Issue by armornet** [DMOJ/judge-server#824]
hello please don't close this ticket until solved.. the team should help us if we face problem.. i am getting the below error.. please suggest
`
root@video:~/judge/.docker# docker run \
>      -v /mnt/problems:/problems \
>     --cap-add=SYS_PTRACE \
>     dmoj/judge-tier1:latest \
>     run -c /problems/judge.yml \
> "$IP" "$JUDGE_NAME" "$JUDGE_AUTHENTICATION_KEY"
Self-testing executors
Self-testing AWK:    Success [0.010s, 940 KB]    awk 1.3.4
Self-testing BF:     Success [0.007s, 528 KB]    bf 1.33.7
Self-testing C:      Success [0.021s, 528 KB]    gcc 10
Self-testing C11:    Success [0.010s, 592 KB]    gcc11 10
Self-testing CPP03:  Success [0.009s, 1540 KB]   g++ 10
Self-testing CPP11:  Success [0.007s, 1536 KB]   g++11 10
Self-testing CPP14:  Success [0.008s, 1608 KB]   g++14 10
Self-testing CPP17:  Success [0.007s, 1540 KB]   g++17 10
Self-testing GAS64:  Success [0.004s, 4 KB]      as_x64 2.35.1, ld_x64 2.35.1
Self-testing JAVA8:  Success [0.341s, 33948 KB]  javac 1.8.0
Self-testing PAS:    Success [0.003s, 4 KB]      fpc 3.2.0
Self-testing PERL:   Success [0.025s, 6036 KB]   perl 5.32.0
Self-testing PY2:    Success [0.043s, 6240 KB]   python 2.7.18
Self-testing PY3:    Success [0.086s, 9600 KB]   python3 3.9.1
Self-testing SED:    Success [0.010s, 792 KB]    sed 4.7
Self-testing TEXT:   Success [0.008s, 1728 KB]   cat 8.32

Running live judge...
INFO 2021-01-07 20:14:03,389 55 packet Preparing to connect to []:9999 as: None
INFO 2021-01-07 20:14:03,389 55 packet TLS not enabled.
INFO 2021-01-07 20:14:03,390 55 packet Opening connection to: []:9999
ERROR 2021-01-07 20:14:03,396 55 packet Connection failed due to socket error: []:9999
Traceback (most recent call last):
  File "/judge/dmoj/packet.py", line 133, in _do_reconnect
    self._connect()
  File "/judge/dmoj/packet.py", line 97, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
WARNING 2021-01-07 20:14:03,397 55 packet Attempting reconnection in 4s: []:9999
INFO 2021-01-07 20:14:07,402 55 packet Opening connection to: []:9999
ERROR 2021-01-07 20:14:07,402 55 packet Connection failed due to socket error: []:9999
Traceback (most recent call last):
  File "/judge/dmoj/packet.py", line 133, in _do_reconnect
    self._connect()
  File "/judge/dmoj/packet.py", line 97, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/judge/dmoj/packet.py", line 133, in _do_reconnect
    self._connect()
  File "/judge/dmoj/packet.py", line 97, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
WARNING 2021-01-07 20:14:07,403 55 packet Attempting reconnection in 6s: []:9999
^CINFO 2021-01-07 20:14:13,406 55 packet Opening connection to: []:9999
ERROR 2021-01-07 20:14:13,407 55 packet Connection failed due to socket error: []:9999
Traceback (most recent call last):
  File "/judge/dmoj/packet.py", line 133, in _do_reconnect
    self._connect()
  File "/judge/dmoj/packet.py", line 97, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

`

**Comment by xsahban** [comment]
I got the same issue
