### ISSUE TITLE
Judge connected but judges none available

### ISSUE THREAD

**Issue by coderamendra** [DMOJ/judge-server#829]
Any help  as my judge is connected and problem showing judges none available ..
In judge.yml i have set the 
**problem_storage_root:
  - /home/sync/problems**
i have also created /sync/problems folder appropriately in home directory but problem is not getting created in the problem storage directory..

please advise

I also referred https://github.com/DMOJ/judge-server/issues/399 but cant understand what is the solution.. 
![error](https://user-images.githubusercontent.com/77751444/105281300-d5e85e00-5bd1-11eb-9c2b-b35876ce1df8.png)

**Comment by fluix-dev** [comment]
The site will upload problems into the directory pointed to by the `DMOJ_PROBLEM_DATA_ROOT` setting, so if both site + judge are on the same machine, it should point to `/home/sync/problems/`.

**Comment by coderamendra** [comment]
yes site and judge are both on same machine... can u let me know where is this setting DMOJ_PROBLEM_DATA_ROOT as i couldn't find in the local_settings.py file

**Comment by kiritofeng** [comment]
It defaults to `None` (value is set in [`settings.py`](https://github.com/DMOJ/online-judge/blob/master/dmoj/settings.py#L60)).
You can overwrite it in `local_settings.py`.

**Comment by coderamendra** [comment]
I did overwrite it in local_settings.py 

DMOJ_PROBLEM_DATA_ROOT = /home/sync/problems/

when restart bridge i get below error
supervisorctl start bridged
bridged: ERROR (spawn error)

when i set DMOJ_PROBLEM_DATA_ROOT = None

bridge starts successfully..

**Comment by fluix-dev** [comment]
You need it to be `"/home/sync/problems/"` so it's a string. Overall, you need to know some basic Python and other skills to run the site+judge successfully, please read [this page](https://dmoj.ca/about/clones/).

**Comment by coderamendra** [comment]
Thank you for your guidance.. yes i did it actually there was a quote error.. now bridge is working.. i have set the DMOJ_PROBLEM_DATA_ROOT and judge.yml paths to /home/sync/problems/ 

but still none judge available for any problem created..  and no problem file getting created in /home/sync/problems

**Comment by fluix-dev** [comment]
Did you upload problems through the site interface?

**Comment by fluix-dev** [comment]
Also, this seems to be going rather quickly and we're quickly going through a variety of problems. If you need further help, it's probably better to turn to `#help-dmoj-setup` on the [Slack](https://slack.dmoj.ca), especially given this isn't an issue with the judge.

**Comment by coderamendra** [comment]
I created the problem through admin panel....

I read your advisory url .. i am not using any clone.. i am using regular dmoj site.. all my installation was smooth and correct.. everything path and config files as stated in the installation page i have done perfectly..  the judge also is connected to site but while creating a problem from admin interface the problem is created in the database but the problem shows none judge available when judge is already connected to the site

**Comment by coderamendra** [comment]
> 
> 
> Also, this seems to be going rather quickly and we're quickly going through a variety of problems. If you need further help, it's probably better to turn to `#help-dmoj-setup` on the [Slack](https://slack.dmoj.ca), especially given this isn't an issue with the judge.

ok thnx let me see if i can get some help from there..

**Comment by coderamendra** [comment]
can you let me know where is the log file of dmoj stored..
