### ISSUE TITLE
Implement new language

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/judge-server#862]
I want to contribute a language to DMOJ (I'm thinking about Scratch now, but it could be some others). Which files I should implement to be ready to review?

**Comment by fluix-dev** [comment]
You're look at creating a new [executor](https://github.com/DMOJ/judge-server/tree/master/dmoj/executors).

**Comment by cuom1999** [comment]
Is it the only place I need to implement? When to use ScriptExecutor and when to write an own executor file?

**Comment by fluix-dev** [comment]
You need to create your own file but may extend from whichever base executor you find appropriate. Comparing to the other existing executors is helpful. This will allow the judge to run $lang code but it won't come preinstalled on DMOJ docker images. To do so, you can add the appropriate installation of $lang to one of the tiers (likely the 3rd) [here](https://github.com/DMOJ/runtimes-docker).
