### ISSUE TITLE
Upgrade Kotlin to 1.6.10

### ISSUE THREAD

**Issue by buthed010203** [DMOJ/judge-server#972]
Kotlin 1.6 came out about a month ago with far better support reading from stdin via `readln()` and `readlnOrNull()`. The currently used version is 1.5.30 which came out in late August which still uses the old `readLine()!!` method for taking input and asserting that it's not null. Would be nice to have this and the various other new features provided in 1.6

*No clue where else to put this issue so I'm just going to drop it here*

**Comment by Xyene** [comment]
The judges rolled to a newer https://github.com/DMOJ/runtimes-docker image, and now have 1.6.10.
