### ISSUE TITLE
judge communication

### ISSUE THREAD

**Issue by ak-soft** [DMOJ/judge-server#980]
I have run DMOJ site as docker composed container (besides Redis and MySql). Try to run judge_base image, it seems it needs internet connection. It stucks at first line of Self-testing:

```
Self-testing executors...
Self-testing AWK:
```

**Comment by ak-soft** [comment]
@quantum5 any idea ?

**Comment by Xyene** [comment]
The `judge_base` image is very outdated (hasn't been updated in 5 years).

The docs have guidance on how to set up a judge with Docker images we currently maintain: https://docs.dmoj.ca/#/judge/setting_up_a_judge?id=with-docker
